- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Adding Local yum Server Repository
      copy:
       content: |
          [base]
          Name="rhel7-main-rpms"
          baseurl=http://192.168.1.34/main/rhel-7-server-rpms
          enabled=1
          gpgcheck=0

          [reposerver-rhel7-optional-rpms]
          name= rhel7-optional-rpms
          baseurl=http://192.168.1.34/optional-rpms/rhel-7-server-optional-rpms
          enabled=1
          gpgcheck=0
          
      dest: /etc/yum.repos/localserver.repo
      tags: repository
    
    - name: Updating all packages - yum
      yum: 
        name: "*"
        state: latest
      
    - name: Adding epel-reposistory from fedora project
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Installing additional base package for redhat 7
      yum: 
        name: "{{ item }}"
        state: latest
        loop:
        - fail2-ban*
        - rear
        - genisoimage
        - syslinux
        - grub2-efi-x64-modules
        




  